image: node:14

before_script:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.74.1/hugo_extended_0.74.1_Linux-64bit.tar.gz | tar xz -C /bin/
  - yarn

test:
  stage: test
  script:
    - yarn test
    - yarn build:prod
