image: node:12

before_script:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_extended_0.57.2_Linux-64bit.tar.gz | tar xz -C /bin/
  - yarn

test:
  stage: test
  script:
    - yarn check
    - yarn build
