image: node:12

before_script:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.58.0/hugo_extended_0.58.0_Linux-64bit.tar.gz | tar xz -C /bin/
  - yarn

test:
  stage: test
  script:
    - yarn test
    - yarn build:prod
